server:
  port: 8888

spring:
  application:
    name: microservicio-configuraciones
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kisito10/aauca-config
          default-label: main
          clone-on-start: true