ARG BUILD_MODULE=microservicio-noticias

FROM maven:3.9-eclipse-temurin-17 AS build
ARG BUILD_MODULE
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl ${BUILD_MODULE} -am

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
ARG BUILD_MODULE
COPY --from=build /app/${BUILD_MODULE}/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]